# mineSQL Paper server properties
level-name=world
level-type=flat
generator-settings={"layers":[{"block":"minecraft:stone","height":124},{"block":"minecraft:bedrock","height":1},{"block":"minecraft:dirt","height":2},{"block":"minecraft:grass_block","height":1}],"biome":"minecraft:plains","structures":{"structures":{}}}
allow-nether=false
spawn-protection=0
spawn-monsters=false
spawn-animals=false
spawn-npcs=false
enable-rcon=false
online-mode=false
difficulty=peaceful
gamemode=creative
force-gamemode=true
allow-flight=true
max-players=20
player-idle-timeout=0
view-distance=10
simulation-distance=10
sync-chunk-writes=false
rate-limit=0
op-permission-level=4
enable-jmx-monitoring=false
pvp=false
enforce-secure-profile=false
motd=mineSQL \u2014 type /sql in chat to query
